import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, Bell, Shield, Radar, Users, Activity, Brain, FileText, Settings, Send, ChevronDown, Eye, Database, LockKeyhole, Zap, CircleDollarSign, MoreHorizontal, Filter, ArrowUpRight } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, ResponsiveContainer, BarChart, Bar, PieChart, Pie, Cell } from 'recharts';
import './styles.css';

const agents = [
  { id:'recon-agent', name:'Recon Agent', status:'active', lob:'CIB', team:'Recon Platform', owner:'Recon Team', mission:'Reconciliation Investigation', model:'Claude 3.5 Sonnet', tools:['Athena','S3','Iceberg'], risk:12, cost:8.24, runs:1422, last:'12 sec ago', x:54, y:30 },
  { id:'fraud-agent', name:'Fraud Agent', status:'investigation', lob:'CCB', team:'Fraud Ops', owner:'Fraud Ops', mission:'Fraud Detection', model:'GPT-4.1', tools:['Jira','Snowflake'], risk:89, cost:21.7, runs:2231, last:'8 sec ago', x:71, y:48 },
  { id:'settlement-agent', name:'Settlement Agent', status:'active', lob:'Payments', team:'Settlement Core', owner:'Payments Team', mission:'Payment Reconciliation', model:'Claude 3 Haiku', tools:['Snowflake'], risk:8, cost:6.8, runs:842, last:'15 sec ago', x:34, y:45 },
  { id:'kyc-verifier', name:'KYC Verifier', status:'idle', lob:'CB', team:'KYC Tech', owner:'KYC Team', mission:'Customer Verification', model:'Titan Text', tools:['DocuSign','S3'], risk:15, cost:3.2, runs:532, last:'18 min ago', x:42, y:62 },
  { id:'ops-assistant', name:'Ops Assistant', status:'awaiting', lob:'CIB', team:'Ops Support', owner:'Ops Team', mission:'Operations Support', model:'Claude 3.5 Sonnet', tools:['ServiceNow','Jira'], risk:5, cost:1.2, runs:122, last:'2 hrs ago', x:27, y:70 },
  { id:'compliance-bot', name:'Compliance Bot', status:'active', lob:'Corporate', team:'Compliance Tech', owner:'Compliance', mission:'Policy Checks', model:'GPT-4o mini', tools:['Confluence'], risk:10, cost:2.6, runs:98, last:'23 sec ago', x:75, y:67 },
  { id:'data-extractor', name:'Data Extractor', status:'idle', lob:'AWM', team:'Data Services', owner:'Data Team', mission:'Data Extraction', model:'Claude 3 Haiku', tools:['S3','Athena'], risk:62, cost:12.4, runs:741, last:'1 hr ago', x:83, y:56 },
  { id:'model-evaluator', name:'Model Evaluator', status:'awaiting', lob:'CIB', team:'AI Enablement', owner:'AI Platform', mission:'Model Quality Review', model:'Llama 3.1', tools:['ModelHub','OpenSearch'], risk:22, cost:4.1, runs:203, last:'33 min ago', x:18, y:34 },
];

const approvals = [
  {agent:'Recon Agent', lob:'CIB', team:'Recon Platform', tool:'jira.createIssue', risk:'Medium', rec:94, model:'Claude 3.5 Sonnet'},
  {agent:'Settlement Agent', lob:'Payments', team:'Settlement Core', tool:'snowflake.export', risk:'Low', rec:89, model:'Claude 3 Haiku'},
  {agent:'Fraud Agent', lob:'CCB', team:'Fraud Ops', tool:'s3.deleteObject', risk:'High', rec:61, model:'GPT-4.1'}
];
const operations = [
  ['10:42:21','Recon Agent','Accessed Athena','Approved'], ['10:42:19','Fraud Agent','Requested Jira Tool','Requires Review'], ['10:42:15','Settlement Agent','Generated Report','Success'], ['10:42:10','KYC Verifier','Accessed Snowflake','Approved'], ['10:42:07','Ops Assistant','Ping','Info'], ['10:42:02','Compliance Bot','Policy Check Complete','Success']
];
const costTrend = [{m:'Jan',v:20},{m:'Feb',v:30},{m:'Mar',v:38},{m:'Apr',v:39},{m:'May',v:48},{m:'Jun',v:52}];
const toolUsage = [{name:'Athena',v:23},{name:'S3',v:18},{name:'Jira',v:17},{name:'Snowflake',v:13},{name:'Iceberg',v:9}];
const riskPie = [{name:'Low',v:82},{name:'Medium',v:45},{name:'High',v:15}];
const statusMeta = {
  active:{label:'Active', cls:'green'}, idle:{label:'Idle', cls:'amber'}, awaiting:{label:'Awaiting Orders', cls:'cyan'}, investigation:{label:'Under Investigation', cls:'red'}
};
function Layout({screen,setScreen,children}){ const nav=[['mission','Mission Control',Radar],['roster','Agent Roster',Users],['profile','Agent Profile',FileText],['governance','Governance',Shield],['threat','Threat Board',Activity],['ai','AI Bureau',Brain],['executive','Executive View',CircleDollarSign]]; return <div className="app"><aside className="sidebar"><div className="brand"><div className="jpm">JPMorganChase</div><div className="product"><Shield size={22}/><span>AGENT<br/>CONTROL BUREAU</span></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setScreen(id)} className={screen===id?'on':''}><Icon size={16}/>{label}</button>)}</nav><div className="sidebarFoot"><div className="avatar">AD</div><div><b>Chief Operator</b><small>CIB Technology</small></div><ChevronDown size={14}/></div></aside><main>{children}</main></div> }
function Header({title,sub,action}){return <header className="top"><div><h1>{title}</h1><p>{sub}</p></div><div className="topActions">{action}<Search size={18}/><Bell size={18}/><div className="avatar sm">AD</div></div></header>}
function Metric({n,l,cls}){return <div className="metric float"><b className={cls||''}>{n}</b><span>{l}</span></div>}
function Mission({setSelected,setScreen}){ const [hover,setHover]=useState(null); const h=hover&&agents.find(a=>a.id===hover); return <><Header title="01 Mission Control" sub="Real-time overview of your digital workforce" action={<button className="askBtn" onClick={()=>setScreen('ai')}><Brain size={15}/> Ask Bureau</button>}/><section className="metricRow"><Metric n="142" l="Total Agents"/><Metric n="37" l="Active" cls="greenText"/><Metric n="82" l="Idle" cls="amberText"/><Metric n="5" l="Awaiting Orders"/><Metric n="2" l="Under Investigation" cls="redText"/></section><section className="missionGrid"><div className="panel radarPanel float"><h2>Agent Field View</h2><div className="radarCanvas"><div className="rings"></div>{agents.map(a=><button key={a.id} className={`agentDot ${statusMeta[a.status].cls}`} style={{left:a.x+'%',top:a.y+'%'}} onMouseEnter={()=>setHover(a.id)} onMouseLeave={()=>setHover(null)} onClick={()=>{setSelected(a);setScreen('profile')}}><span>{a.name}</span></button>)}{h&&<div className="hoverCard" style={{left:`min(${h.x+3}%, 68%)`, top:`min(${h.y+6}%, 68%)`}}><b>{h.name}</b><small>{h.team} · {h.lob}</small><small>Model: {h.model}</small><small>Risk: {h.risk} · Last: {h.last}</small></div>}</div><div className="legend"><span className="dot green"></span>Active <span className="dot amber"></span>Idle <span className="dot cyan"></span>Awaiting Orders <span className="dot red"></span>Under Investigation</div></div><div className="panel float ops"><h2>Operations Log <a>View all</a></h2>{operations.map((o,i)=><div className="op" key={i}><span>{o[0]}</span><b>{o[1]}</b><small>{o[2]}</small><em className={o[3].toLowerCase().replace(' ','')}>{o[3]}</em></div>)}</div></section><div className="commandBar float"><Brain size={21}/><input placeholder="Ask the Bureau anything..." onFocus={()=>setScreen('ai')}/><button>Which agents use Athena?</button><button>Show high risk agents</button><button>New tools detected today?</button><Send size={19}/></div></>}
function Roster({setSelected,setScreen}){return <><Header title="02 Agent Roster" sub="Digital workforce directory" action={<button className="outline"><Filter size={14}/> Filters</button>}/><div className="filters"><input placeholder="Search agents..."/><select><option>All LOBs</option></select><select><option>All Status</option></select><select><option>All Models</option></select></div><h3>Active Agents</h3><div className="cards">{agents.map(a=><button key={a.id} className="agentCard float" onClick={()=>{setSelected(a);setScreen('profile')}}><div><span className={`dot ${statusMeta[a.status].cls}`}></span><b>{a.name}</b><MoreHorizontal size={16}/></div><small>Mission</small><p>{a.mission}</p><div className="metaGrid"><span>LOB<b>{a.lob}</b></span><span>Team<b>{a.team}</b></span><span>Model<b>{a.model}</b></span><span>Risk<b>{a.risk} {a.risk>60?'High':'Low'}</b></span></div></button>)}</div></>}
function Profile({agent}){ const a=agent||agents[0]; return <><Header title="03 Agent Profile" sub={`${a.lob} · ${a.team} · ${a.model}`} action={<button className="outline">Actions <ChevronDown size={14}/></button>}/><div className="profileHead float"><div><h1>{a.name} <span className={`pill ${statusMeta[a.status].cls}`}>{statusMeta[a.status].label}</span></h1><p>Mission: {a.mission} · Owner: {a.owner}</p></div><Metric n={a.risk} l="Risk Score"/><Metric n={a.runs.toLocaleString()} l="Runs Today"/><Metric n={`$${a.cost}`} l="Cost Today"/></div><div className="three"><div className="panel float"><h2>Agent Summary</h2><dl><dt>LOB</dt><dd>{a.lob}</dd><dt>Team</dt><dd>{a.team}</dd><dt>Model</dt><dd>{a.model}</dd><dt>Security Clearance</dt><dd className="greenText">Approved</dd></dl></div><div className="panel float"><h2>Recent Operations</h2>{operations.slice(0,5).map((o,i)=><div className="row" key={i}><span>{o[0]}</span><b>{o[2]}</b><em className="greenText">Success</em></div>)}</div><div className="panel float"><h2>Tools & Permissions</h2>{a.tools.map(t=><div className="row" key={t}><Database size={14}/><b>{t}</b><em className="greenText">Approved</em></div>)}</div></div></>}
function Governance(){return <><Header title="04 Governance Center" sub="Review and approve new tools and permissions"/><div className="panel float"><div className="tabs"><b>Pending (3)</b><span>Approved</span><span>Rejected</span><span>All Requests</span></div>{approvals.map(x=><div className="approval" key={x.tool}><div><LockKeyhole size={18}/><b>{x.agent}</b><small>{x.team} · {x.lob}</small><p>{x.tool}</p></div><div><small>Model</small><b>{x.model}</b></div><div><small>AI Recommendation</small><strong>{x.rec}%</strong><small>Similar to approved tools</small></div><div><small>Risk</small><span className={x.risk==='High'?'redText':x.risk==='Medium'?'amberText':'greenText'}>{x.risk}</span></div><div><button className="approve">Approve</button><button className="reject">Reject</button></div></div>)}</div></>}
function Threat(){return <><Header title="05 Threat Board" sub="Monitor risk and policy violations"/><div className="threatGrid"><div className="panel float threatRadar"><div className="rings redrings"></div><h1>2</h1><p>ACTIVE THREATS</p></div><div className="panel float">{agents.filter(a=>a.risk>30).map(a=><div className="threat" key={a.id}><b>{a.name}</b><small>{a.team} · {a.lob} · {a.model}</small><p>{a.risk>70?'Unauthorized tool usage':'Elevated data access'}</p><strong>{a.risk}</strong></div>)}</div></div></>}
function AIBureau(){return <><Header title="06 AI Bureau" sub="Ask questions. Get governance intelligence."/><div className="aiGrid"><div className="panel float prompts"><h2>Suggested Questions</h2>{['Which agents use Athena?','Show high risk agents','What are new tools this week?','Do we have duplicate agents?','Show agents by LOB'].map(q=><button key={q}>{q}<ArrowUpRight size={13}/></button>)}</div><div className="panel float chat"><div className="bubble me">Which agents use Athena?</div><div className="bubble bot"><b>23 agents are currently using Athena.</b><ol><li>Recon Agent — CIB / Recon Platform</li><li>Fraud Agent — CCB / Fraud Ops</li><li>Data Extractor — AWM / Data Services</li></ol><p>Common models: Claude 3.5 Sonnet, Claude 3 Haiku.</p><strong>Estimated Monthly Cost: $4,320</strong></div><div className="miniRadar"><div className="rings"></div>{agents.slice(0,6).map(a=><span key={a.id} className={`dot ${statusMeta[a.status].cls}`} style={{left:a.x+'%',top:a.y+'%'}}></span>)}</div><div className="chatInput"><input placeholder="Ask anything about your agents..."/><Send size={18}/></div></div></div></>}
function Executive(){return <><Header title="07 Executive View" sub="High level summary for leadership"/><section className="metricRow"><Metric n="142" l="Total Agents"/><Metric n="37" l="Active" cls="greenText"/><Metric n="12" l="Duplicate Agents"/><Metric n="5" l="Pending Approvals"/><Metric n="$42K" l="Monthly Cost"/></section><div className="execGrid"><div className="panel float"><h2>Cost Trend</h2><ResponsiveContainer width="100%" height={180}><LineChart data={costTrend}><XAxis dataKey="m"/><YAxis/><Line dataKey="v" stroke="currentColor" strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="panel float"><h2>Risk Distribution</h2><ResponsiveContainer width="100%" height={180}><PieChart><Pie data={riskPie} dataKey="v" innerRadius={52} outerRadius={78}>{riskPie.map((_,i)=><Cell key={i} fill={['#7dd37d','#e6b450','#e25555'][i]}/>)}</Pie></PieChart></ResponsiveContainer></div><div className="panel float"><h2>Top Tools by Usage</h2><ResponsiveContainer width="100%" height={180}><BarChart data={toolUsage} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="name"/><Bar dataKey="v" fill="currentColor"/></BarChart></ResponsiveContainer></div></div></>}
function App(){ const [screen,setScreen]=useState('mission'); const [selected,setSelected]=useState(agents[0]); const page={mission:<Mission setSelected={setSelected} setScreen={setScreen}/>,roster:<Roster setSelected={setSelected} setScreen={setScreen}/>,profile:<Profile agent={selected}/>,governance:<Governance/>,threat:<Threat/>,ai:<AIBureau/>,executive:<Executive/>}[screen]; return <Layout screen={screen} setScreen={setScreen}>{page}</Layout> }
createRoot(document.getElementById('root')).render(<App/>);
